//
//  HeatmapView.swift
//  Habitator
//
//  Created by Nyein Nyein on 19/11/21.
//

import SwiftUI

struct HeatmapView: View {
    @Binding var current: Int?
    @Binding var habits: [Habit]
    var body: some View {
        VStack {
            Text("Habits")
                .font(.system(size: 30, weight: .bold))
            Divider()
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            HStack{
                Rectangle()
                    .frame(width:30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
                Rectangle()
                    .frame(width: 30, height: 30)
            }
            Spacer()
        }
    }
}


